const actionTypes ={

    ADD_TO_CART:'ADD_TO_CART',
    REMOVE_CART_ITEM:'REMOVE_CART_ITEM',
    EMPTY_CART:'EMPTY_CART',    
    DECREMENT_ITEM_QTY:'DECREMENT_ITEM_QTY',
    INCREMENT_ITEM_QTY:'INCREMENT_ITEM_QTY',
    CONFIRM_ORDER:'CONFIRM_ORDER'
}

export default actionTypes